from enum import Enum


class DataProc(Enum):
    EXPECTED_VALUES = "expected_values"
    MIN = "min"
    MAX = "max"
    IMPUTATION = "imputation"
    OUTLIER_REMOVAL = "outlier_removal"
    TRANSFORMATION = "transformation"
    GROUPBY = "groupby"
    TARGET_FIELD = "target_field"
    FLAG_IMPUTED = "flag_imputed"
    BINNING = "binning"
    TYPE = "type"
    METHOD = "method"
    MEAN = "mean"
    MEDIAN = "median"
    MODE = "mode"
    Z_TRANSFORM = "z_transform"
    PERCENTILE = "percentile"
    REPLACE = "replace"
    AGGREGATE = "aggregate"
    IMPUTATION_FLAG_SUFFIX = "IMPUTATION_FLAG"
    ASCENDING = "ascending"
    LABEL_ENCODING = "label_encoding"
    FIT = "fit"
    FIELD_MEAN_TRANSFORMER = "field_mean_transformer"
    PATH = "path"
    LOWER_PCT = "lower_pct"
    UPPER_PCT = "upper_pct"
